from yacs.config import CfgNode as CN

_C = CN()

_C.NAME = ''
_C.DATA_DIR = ''
_C.PRINT_FREQ = 50

_C.DATA = CN()

_C.DATA.FDIM = 71
_C.DATA.TESTRATIO = 0.2
_C.DATA.TRAINBS = 256
_C.DATA.TESTBS = 1024

_C.USE_AE = False
_C.MTASK = False
_C.PRED = 'MLP'

_C.MODEL = CN()

_C.MODEL.G = CN()
_C.MODEL.G.LR = 0.001
_C.MODEL.G.IN_DIM = 0
_C.MODEL.G.EPOCH = 35
_C.MODEL.G.USE_BN = False
_C.MODEL.G.STRUCTURE = [128, 256, 256, 64]


_C.MODEL.TD = CN()
_C.MODEL.TD.LR = 0.001
_C.MODEL.TD.IN_DIM = 0
_C.MODEL.TD.EPOCH = 35
_C.MODEL.TD.USE_BN = False
_C.MODEL.TD.STRUCTURE = [128, 256, 256, 64]

_C.MODEL.X = CN()
_C.MODEL.X.LR = 0.001
_C.MODEL.X.IN_DIM = 0
_C.MODEL.X.EPOCH = 35
_C.MODEL.X.USE_BN = False
_C.MODEL.X.STRUCTURE = [64, 256, 256, 64, 16]

_C.MODEL.AE = CN()
_C.MODEL.AE.LR = 0.001
_C.MODEL.AE.IN_DIM = 0
_C.MODEL.AE.EPOCH = 35
_C.MODEL.AE.USE_BN = False
_C.MODEL.AE.LAT_D = 16
_C.MODEL.AE.STRUCTURE = [128, 256, 256, 64]

_C.MODEL.ATT = CN()
_C.MODEL.ATT.LR = 0.001
_C.MODEL.ATT.EPOCH = 35
_C.MODEL.ATT.USE_BN = False
_C.MODEL.ATT.NHEAD = 4
_C.MODEL.ATT.QKV_STRUCTURE = [128, 256, 256, 64]
_C.MODEL.ATT.OUTP_CHN = [8, 1]

def get_default_cfg():
    return _C.clone()
