NAME: 'attention'
DATA_DIR: 'raw_data/11oLpHcL/synthesized'
PRED: 'ATT'
PRETRAIN_DIR: 'DeciNet/pretrained/ap_pred.th'

DATA:
  TRAINBS: 32
  TESTBS: 32

MODEL:
  GAT:
    LR: 0.001
    EPOCH: 20
    AGG:
      NHEAD: 4
