NAME: 'GAT_dloss'
DATA_DIR: 'raw_data/11oLpHcL/synthesized'
PRED: 'ATT'
PRETRAIN_DIR: 'DeciNet/pretrained/ap_pred.th'

W_SCORE: 1.
W_DIRE: 0.2
W_VELO: 0.01

DATA:
  TRAINBS: 64
  TESTBS: 64

MODEL:
  GAT:
    LR: 0.002
    EPOCH: 20
    AGG:
      NHEAD: 4
      POOLING: 'Avg'
  ATT:
    LR: 0.001
    EPOCH: 10
    NHEAD: 4
    USE_BN: True
    QKV_STRUCTURE: [16, 64, 128, 64, 16]
    OUTP_CHN: [8, 1]
