NAME: 'attention'
DATA_DIR: 'raw_data/11oLpHcL/synthesized'
PRED: 'ATT'
PRETRAIN_DIR: 'DeciNet/pretrained/ap_pred.th'

DATA:
  TRAINBS: 16
  TESTBS: 16

MODEL:
  GAT:
    LR: 0.001
    EPOCH: 20
    AGG:
      NHEAD: 4
  ATT:
    LR: 0.001
    EPOCH: 10
    NHEAD: 4
    USE_BN: True
    QKV_STRUCTURE: [16, 64, 128, 64, 16]
    OUTP_CHN: [8, 1]
